import "./globals.css";
import { JetBrains_Mono } from "next/font/google";
import { twMerge as tw } from "tailwind-merge";

const font = JetBrains_Mono({ subsets: ["latin"], variable: "--font" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={tw(font.variable, "font-mono")}>{children}</body>
    </html>
  );
}
